-- 코드를 입력하세요

WITH REVIEW_RANK AS (
SELECT MEMBER_ID, COUNT(REVIEW_ID), DENSE_RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) as rank
FROM REST_REVIEW
GROUP BY MEMBER_ID
    )
SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'yyyy-mm-dd') as REVIEW_DATE
FROM MEMBER_PROFILE mp, REST_REVIEW rr
WHERE mp.MEMBER_ID = rr.MEMBER_ID and mp.MEMBER_ID IN (SELECT MEMBER_ID FROM REVIEW_RANK WHERE rank = 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT
