-- 코드를 입력하세요

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM AUTHOR a NATURAL JOIN (
SELECT AUTHOR_ID, CATEGORY, SUM(total) as TOTAL_SALES
FROM (
SELECT b.CATEGORY, b.AUTHOR_ID, b.PRICE, bs.SALES, PRICE * SALES as total
FROM BOOK b,
(
SELECT BOOK_ID, SALES
FROM BOOK_SALES
WHERE TO_CHAR(SALES_DATE, 'yyyy-mm') = '2022-01'
) bs
WHERE b.BOOK_ID = bs.BOOK_ID
    )
GROUP BY AUTHOR_ID, CATEGORY
)
ORDER BY AUTHOR_ID, CATEGORY DESC