-- 코드를 입력하세요

SELECT PRODUCT_CODE, (total * price) as SALES
FROM(
SELECT PRODUCT_ID, sum(sales_amount) as total
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID
    ) NATURAL JOIN PRODUCT
ORDER BY SALES DESC, PRODUCT_CODE